image: elixir:1.13
build:
  stage: build
  variables:
    MIX_ENV: test
  only:
    changes:
      - c_src/**
      - lib/**
      - test/**
      - '*.exs'
      - mix.lock
      - .gitlab-ci.yml
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix test
